[package]
name = "openpgp"
version = "0.1.0"
authors = ["Pierre-Étienne Meunier <pe@pijul.org>"]

[dependencies]
log = "0.3"
byteorder = "0.5"
rustc-serialize = "0.3"
libc = "0.2"
bitflags = "0.7"
openssl = "0.7"
flate2 = "0.2"

[dev-dependencies]
env_logger = "0.3"
rand = "0.3"
